export const TableApi = [
    {
        id: 1,
        examName: "upsc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 2,
        examName: "upsc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 3,
        examName: "upsc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/255px-Flag_of_India.svg.pnghttps://upsc.gov.in/examinations/Combined%20Defence%20Services%20Examination%20%28I%29%2C%202022",
    },
    {
        id: 4,
        examName: "ssc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 5,
        examName: "ssc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 6,
        examName: "ssc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 7,
        examName: "upsc",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 8,
        examName: "railway",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 9,
        examName: "railway",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 10,
        examName: "railway",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 11,
        examName: "Bank",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 12,
        examName: "Bank",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 13,
        examName: "Bank",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 14,
        examName: "Bank",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 15,
        examName: "Bank",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    {
        id: 16,
        examName: "UPSC CDS",
        postName: "IAS Officer, IPS Officer & Other",
        totalPost: "16002",
        applyDate: "31 aug 2023",
        lastDate: "1 sept 2023 Midnight",
        link: "https://upsc.gov.in/",
    },
    
];
